version: "3.9"
services:
  db:
    container_name: db.ror-beginners-api
    build: "build/mysql"
    platform: linux/amd64
    ports:
      - "${MYSQL_PORT}:3306"
    restart: always
    volumes:
      - ./tmp/tmp_mysql:/tmp
      - ./tmp/src-db_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      MYSQL_DATABASE: src-begin-db
      MYSQL_USER: ror_user
      MYSQL_PASSWORD: ror_pass
    command: mysqld --sql_mode=""

  web:
    container_name: web.ror-beginners-api
    build:
      context: .
      dockerfile: build/web/Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/opt/src
    ports:
      - "${WEB_PORT}:3000"
    depends_on:
      - db
    environment:
      - TZ=UTC
    # pry debugging need these settings
    tty: true
    stdin_open: true